"""empty message

Revision ID: 2101e05df65c
Revises: 22688e17e1f4
Create Date: 2021-10-21 02:21:45.062399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2101e05df65c'
down_revision = '22688e17e1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite__character', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('favorite__character', 'character_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorite__character', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('favorite__planet', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('favorite__planet', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorite__planet', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'favorite__planet', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favorite__planet', 'planet', ['planet_id'], ['id'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorite__planet', type_='foreignkey')
    op.drop_constraint(None, 'favorite__planet', type_='foreignkey')
    op.alter_column('favorite__planet', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorite__planet', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('favorite__planet', 'id')
    op.alter_column('favorite__character', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorite__character', 'character_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('favorite__character', 'id')
    # ### end Alembic commands ###
