"""empty message

Revision ID: 22688e17e1f4
Revises: f5f7718bcf3f
Create Date: 2021-10-21 01:21:17.966851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22688e17e1f4'
down_revision = 'f5f7718bcf3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__planet',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    op.create_table('favorite__character',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite__character')
    op.drop_table('favorite__planet')
    # ### end Alembic commands ###
